language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6

install:
  - sudo apt-get install -y build-essential cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make 

