language: cpp
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data

install:
  - sudo apt-get install -y build-essential cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make 

